class_name Discovered3
extends RefCounted
## GENERATED by tools/run_depth.gd — do not hand-edit.
##
## The best route-set the depth search found per level, in the same shape as
## Scenarios3: a cell polyline per card, or {"cells", "closed"} for a loop.
## The level select shows a WATCH BEST button for every level listed here, so
## optimizer output gets EYEBALLED rather than trusted numerically
## (docs/autodesign-research.md §5.3 step 4).

const SETS := {
	"L1": {
		"desc": "search elite: 0 loop(s), 12 stops, 44 cells (beat thesis +9.8)",
		"score": 1253.70,
		"routes": [
			[Vector2i(3, 9), Vector2i(3, 8), Vector2i(3, 7), Vector2i(3, 6), Vector2i(3, 5), Vector2i(3, 4), Vector2i(3, 3), Vector2i(3, 2), Vector2i(3, 1), Vector2i(3, 0), Vector2i(2, 0), Vector2i(1, 0), Vector2i(1, 1), Vector2i(1, 2), Vector2i(0, 2)],
			[Vector2i(0, 8), Vector2i(0, 7), Vector2i(0, 6), Vector2i(0, 5), Vector2i(0, 4), Vector2i(1, 4), Vector2i(1, 3), Vector2i(1, 2), Vector2i(1, 1), Vector2i(1, 0), Vector2i(2, 0), Vector2i(3, 0), Vector2i(4, 0), Vector2i(5, 0), Vector2i(5, 1), Vector2i(5, 2), Vector2i(6, 2)],
			[Vector2i(3, 0), Vector2i(4, 0), Vector2i(5, 0), Vector2i(5, 1), Vector2i(5, 2), Vector2i(5, 3), Vector2i(5, 4), Vector2i(6, 4), Vector2i(6, 5), Vector2i(6, 6), Vector2i(6, 7), Vector2i(6, 8)],
		],
	},
	"L2": {
		"desc": "search elite: 2 loop(s), 16 stops, 48 cells (beat thesis +6.6)",
		"score": 1250.80,
		"routes": [
			{"closed": true, "cells": [Vector2i(1, 7), Vector2i(0, 7), Vector2i(0, 8), Vector2i(0, 9), Vector2i(1, 9), Vector2i(1, 8)]},
			[Vector2i(0, 7), Vector2i(0, 6), Vector2i(0, 5), Vector2i(0, 4), Vector2i(0, 3), Vector2i(0, 2), Vector2i(1, 2), Vector2i(1, 1), Vector2i(1, 0), Vector2i(0, 0)],
			{"closed": true, "cells": [Vector2i(0, 2), Vector2i(0, 1), Vector2i(0, 0), Vector2i(1, 0), Vector2i(2, 0), Vector2i(3, 0), Vector2i(4, 0), Vector2i(5, 0), Vector2i(6, 0), Vector2i(7, 0), Vector2i(7, 1), Vector2i(7, 2), Vector2i(7, 3), Vector2i(7, 4), Vector2i(7, 5), Vector2i(7, 6), Vector2i(7, 7), Vector2i(7, 8), Vector2i(7, 9), Vector2i(6, 9), Vector2i(5, 9), Vector2i(4, 9), Vector2i(3, 9), Vector2i(2, 9), Vector2i(1, 9), Vector2i(0, 9), Vector2i(0, 8), Vector2i(0, 7), Vector2i(0, 6), Vector2i(0, 5), Vector2i(0, 4), Vector2i(0, 3)]},
		],
	},
	"L3": {
		"desc": "search elite: 0 loop(s), 11 stops, 22 cells (beat thesis +0.0)",
		"score": 1268.40,
		"routes": [
			[Vector2i(1, 3), Vector2i(2, 3), Vector2i(3, 3), Vector2i(3, 2), Vector2i(3, 1), Vector2i(3, 0)],
			[Vector2i(5, 3), Vector2i(4, 3), Vector2i(3, 3), Vector2i(3, 2), Vector2i(3, 1), Vector2i(3, 0)],
			[Vector2i(3, 0), Vector2i(3, 1), Vector2i(3, 2), Vector2i(3, 3), Vector2i(3, 4), Vector2i(3, 5), Vector2i(3, 6), Vector2i(3, 7), Vector2i(3, 8), Vector2i(3, 9)],
		],
	},
	"L4": {
		"desc": "search elite: 3 loop(s), 15 stops, 76 cells (beat thesis +4.6)",
		"score": 1266.40,
		"routes": [
			{"closed": true, "cells": [Vector2i(2, 0), Vector2i(3, 0), Vector2i(4, 0), Vector2i(5, 0), Vector2i(5, 1), Vector2i(6, 1), Vector2i(6, 2), Vector2i(7, 2), Vector2i(7, 3), Vector2i(7, 4), Vector2i(7, 5), Vector2i(7, 6), Vector2i(7, 7), Vector2i(6, 7), Vector2i(5, 7), Vector2i(4, 7), Vector2i(3, 7), Vector2i(2, 7), Vector2i(2, 6), Vector2i(1, 6), Vector2i(1, 5), Vector2i(0, 5), Vector2i(0, 4), Vector2i(1, 4), Vector2i(1, 3), Vector2i(1, 2), Vector2i(1, 1), Vector2i(2, 1)]},
			{"closed": true, "cells": [Vector2i(0, 2), Vector2i(0, 3), Vector2i(0, 4), Vector2i(0, 5), Vector2i(0, 6), Vector2i(1, 6), Vector2i(2, 6), Vector2i(3, 6), Vector2i(4, 6), Vector2i(5, 6), Vector2i(6, 6), Vector2i(7, 6), Vector2i(7, 5), Vector2i(7, 4), Vector2i(7, 3), Vector2i(7, 2), Vector2i(7, 1), Vector2i(6, 1), Vector2i(5, 1), Vector2i(4, 1), Vector2i(3, 1), Vector2i(2, 1), Vector2i(1, 1), Vector2i(1, 2)]},
			{"closed": true, "cells": [Vector2i(5, 7), Vector2i(6, 7), Vector2i(6, 6), Vector2i(6, 5), Vector2i(6, 4), Vector2i(6, 3), Vector2i(6, 2), Vector2i(6, 1), Vector2i(6, 0), Vector2i(5, 0), Vector2i(4, 0), Vector2i(3, 0), Vector2i(2, 0), Vector2i(2, 1), Vector2i(1, 1), Vector2i(1, 2), Vector2i(1, 3), Vector2i(1, 4), Vector2i(1, 5), Vector2i(1, 6), Vector2i(1, 7), Vector2i(2, 7), Vector2i(3, 7), Vector2i(4, 7)]},
		],
	},
	"X-1": {
		"desc": "search elite: 2 loop(s), 28 stops, 94 cells (beat thesis +33.5)",
		"score": 1220.60,
		"routes": [
			[Vector2i(2, 0), Vector2i(1, 0), Vector2i(0, 0), Vector2i(0, 1), Vector2i(0, 2), Vector2i(0, 3), Vector2i(1, 3), Vector2i(2, 3), Vector2i(3, 3), Vector2i(4, 3), Vector2i(4, 4), Vector2i(4, 5), Vector2i(4, 6), Vector2i(4, 7), Vector2i(4, 8), Vector2i(4, 9), Vector2i(5, 9), Vector2i(6, 9)],
			{"closed": true, "cells": [Vector2i(6, 7), Vector2i(6, 6), Vector2i(6, 5), Vector2i(5, 5), Vector2i(4, 5), Vector2i(4, 4), Vector2i(4, 3), Vector2i(5, 3), Vector2i(6, 3), Vector2i(6, 2), Vector2i(6, 1), Vector2i(6, 0), Vector2i(5, 0), Vector2i(4, 0), Vector2i(3, 0), Vector2i(2, 0), Vector2i(2, 1), Vector2i(2, 2), Vector2i(2, 3), Vector2i(2, 4), Vector2i(2, 5), Vector2i(1, 5), Vector2i(0, 5), Vector2i(0, 6), Vector2i(0, 7), Vector2i(0, 8), Vector2i(0, 9), Vector2i(1, 9), Vector2i(2, 9), Vector2i(2, 8), Vector2i(2, 7), Vector2i(3, 7), Vector2i(4, 7), Vector2i(4, 8), Vector2i(4, 9), Vector2i(5, 9), Vector2i(6, 9), Vector2i(6, 8)]},
			{"closed": true, "cells": [Vector2i(6, 0), Vector2i(6, 1), Vector2i(6, 2), Vector2i(6, 3), Vector2i(5, 3), Vector2i(4, 3), Vector2i(4, 4), Vector2i(4, 5), Vector2i(5, 5), Vector2i(6, 5), Vector2i(6, 6), Vector2i(6, 7), Vector2i(6, 8), Vector2i(6, 9), Vector2i(5, 9), Vector2i(4, 9), Vector2i(4, 8), Vector2i(4, 7), Vector2i(3, 7), Vector2i(2, 7), Vector2i(2, 8), Vector2i(2, 9), Vector2i(1, 9), Vector2i(0, 9), Vector2i(0, 8), Vector2i(0, 7), Vector2i(0, 6), Vector2i(0, 5), Vector2i(1, 5), Vector2i(2, 5), Vector2i(2, 4), Vector2i(2, 3), Vector2i(2, 2), Vector2i(2, 1), Vector2i(2, 0), Vector2i(3, 0), Vector2i(4, 0), Vector2i(5, 0)]},
		],
	},
}


static func has(level_id: String) -> bool:
	return SETS.has(level_id)


## Route entries for a level (same shape Scenarios3.route_set returns).
static func route_set(level_id: String) -> Array:
	return SETS.get(level_id, {}).get("routes", [])


static func desc(level_id: String) -> String:
	return SETS.get(level_id, {}).get("desc", "")
