class_name Discovered3
extends RefCounted
## GENERATED by tools/run_depth.gd — do not hand-edit.
##
## The best route-set the depth search found per level, in the same shape as
## Scenarios3: a cell polyline per card, or {"cells", "closed"} for a loop.
## The level select shows a WATCH BEST button for every level listed here, so
## optimizer output gets EYEBALLED rather than trusted numerically
## (docs/autodesign-research.md §5.3 step 4).

const SETS := {
	"L3": {
		"desc": "search elite: 0 loop(s), 10 stops, 24 cells (beat thesis +1088.9)",
		"score": 1153.80,
		"routes": [
			[Vector2i(3, 0), Vector2i(3, 1), Vector2i(3, 2), Vector2i(3, 3), Vector2i(4, 3), Vector2i(5, 3)],
			[Vector2i(5, 3), Vector2i(5, 4), Vector2i(5, 5), Vector2i(5, 6), Vector2i(5, 7), Vector2i(5, 8), Vector2i(4, 8), Vector2i(3, 8), Vector2i(3, 9)],
			[Vector2i(3, 9), Vector2i(3, 8), Vector2i(3, 7), Vector2i(3, 6), Vector2i(3, 5), Vector2i(3, 4), Vector2i(3, 3), Vector2i(2, 3), Vector2i(1, 3)],
		],
	},
}


static func has(level_id: String) -> bool:
	return SETS.has(level_id)


## Route entries for a level (same shape Scenarios3.route_set returns).
static func route_set(level_id: String) -> Array:
	return SETS.get(level_id, {}).get("routes", [])


static func desc(level_id: String) -> String:
	return SETS.get(level_id, {}).get("desc", "")
