extends Node2D
## Game controller for prototype v3 "Path Drawing".
## Owns: the level config (data-driven via Levels3), the three route cards +
## cars, drag-to-draw route editing, the gate FIFO mutexes, PULSE-based
## passenger spawning + time-based replanning, the phase machine below, and
## the game time scale (pause/1x/3x - a plain variable multiplied into game
## ticks).
##
## ------------------------------------------------- THE v4 LOOP: plan, then run
##
## design -> commit -> watch -> learn -> retry. There is NO mid-run editing:
##
##   BRIEFING  the level's thesis line, the elevator ROSTER you get and the
##             passenger MIX to expect (hud3 reads both straight out of the
##             level data, so a briefing can never drift from what spawns).
##             No clock, no passengers.        -> PLAN
##   PLAN      the grid is fully editable and NOTHING is running: no clock, no
##             passengers, no spawner. Draw / redraw / clear freely.
##             -> RUN, gated on ready_to_run() (every card has a route with
##             >= 2 room stops).
##   PLAYING   the run. can_edit() is false, so every editing path - taps,
##             drags, CLEAR, chip selection, commit_route() itself - refuses.
##             Speed controls stay live; watching is the point now.
##             -> ABORT back to PLAN (counters reset, routes kept).
##   WIN/LOSE  the result overlay + stats. -> RETRY (back to PLAN with the
##             routes intact), NEXT LEVEL (win only), LEVELS.
##
## Because EVERY commit now happens in PLAN, every car deploys INSTANTLY
## (commit_route -> Car3.set_route). Car3's recall -> ghost-countdown ->
## redeploy machinery is still correct and still tested, but it is out of the
## main loop: only commit_route_mid_run() can reach it, and nothing in the
## player flow calls that. See car3.gd and commit_route_mid_run() below.
##
## Watch mode (Levels3.watch_strategy) skips BRIEFING/PLAN entirely: the
## scenario routes are committed and the run starts at once.
##
## All randomness flows through `rng` (one RandomNumberGenerator): normal
## play randomizes it, the balance harness sets a fixed seed for
## deterministic runs.

## PLAYING is the RUN phase; WIN/LOSE together are the RESULT phase. The names
## are kept because the harness and the depth tools test against them.
enum State { BRIEFING, PLAN, PLAYING, WIN, LOSE }

## Safety bound on one magnetic-extend walk (a drag sample can never legitimately
## cross more cells than the grid holds; each step is strictly closer anyway).
const MAX_STROKE_WALK := 256

var level: Dictionary = {} # Levels3 entry for Levels3.current
var CARDS: Array = [] # this level's 3 elevator cards
var QUOTA := 30
var MAX_LOST := 8

var state: int = State.BRIEFING
var time_scale := 1.0
var served := 0
var lost := 0
var elapsed := 0.0 # game-time seconds since session start (drives spawn ramp)
var auto_spawn := true # test hook: harness may disable random spawns
var endless := false # after a win, "keep playing" disables win/lose checks

## Simulated/headless run: _process must not tick the game, because the
## harness drives advance() itself. Measured drift with _process left on:
## +0.047 game-s per engine frame a run stays alive (docs/sim-search-
## feasibility.md §2). Set it AFTER instantiate() and BEFORE add_child().
var headless := false

var rng := RandomNumberGenerator.new()

# Pulse spawner state: quiet until pulse_timer runs out, then a burst of
# burst_left passengers spawns gap seconds apart.
var pulse_timer := 0.0
var burst_left := 0
var burst_timer := 0.0

## "" (normal play) | "naive" | "thesis" | "best" (from Levels3.watch_strategy).
## "best" replays the route-set the depth search discovered (Discovered3,
## generated by tools/run_depth.gd) on the SAME canonical seed as naive and
## thesis, so all three face the identical demand sequence.
var watch := ""

## PERF (v3.5): the per-tick passenger loop iterates THIS list, not
## passengers_node.get_children() — queue_free() does not flush until an
## engine frame ends, and a headless run does a whole session inside one
## frame, so up to ~80 % of the children were dead nodes (measured).
## Served/expired passengers are compacted out at the end of advance(), never
## mid-iteration. Same order, same ticks: dead passengers already returned
## immediately from tick().
var active_passengers: Array = []
var _passengers_dirty := false

var routes: Array = [null, null, null] # Route3 or null per card
var cars: Array = [null, null, null] # Car3 per card (always exist, may be idle)
## gate GROUP index -> {"width": int, "used": int, "holders": Array[Car3],
## "queue": Array[Car3]} - see gate_request().
var gates := {}
var waiting := {} # room cell -> Array[Passenger3] in arrival order

# Session log for stats/harness: one entry per finished passenger,
# {"type", "origin", "dest", "wait", "rides"}.
var log_served: Array = []
var log_lost: Array = []

var selected_card := -1
var drawing := false
var stroke: Array = [] # Vector2i cells of the active drag
var stroke_closed := false # live stroke closed back onto stroke[0] (a loop)

## Corridor-rejection UX (v4). When a commit is refused because the car is too
## wide for a corridor on the route (or any other geometry error a programmatic
## caller slipped through), the reason is parked here and hud3 surfaces it on
## the hint line, in the card's colour, until reject_until_ms. The magnetic
## drawing head treats a too-narrow corridor cell as a wall for the selected
## car (felt as resistance), so this hint is the fallback for the fast-drag /
## straight-fill path that reaches the cell anyway, and for programmatic
## callers (watch mode, harness, depth tools) that commit a bad route directly.
var reject_msg := ""
var reject_card := -1
var reject_until_ms := 0

@onready var grid: Grid3 = $Grid
@onready var cars_node: Node2D = $Cars
@onready var passengers_node: Node2D = $Passengers
@onready var hud: CanvasLayer = $HUD


func _ready() -> void:
	if headless:
		set_process(false) # the harness owns the clock; see `headless` above
	level = Levels3.get_level(Levels3.current)
	watch = Levels3.watch_strategy
	Grid3.load_level(level.rows)
	CARDS = level.cards
	QUOTA = level.quota
	MAX_LOST = level.max_lost
	routes = []
	cars = []
	for gi in Grid3.gate_groups().size():
		gates[gi] = {"width": Grid3.gate_group_width(gi), "used": 0,
				"holders": [], "queue": []}
	for r in Grid3.rooms():
		waiting[r] = []
	grid.game = self
	hud.game = self
	for i in CARDS.size():
		routes.append(null)
		var c := Car3.new()
		c.setup(self, i, CARDS[i])
		cars_node.add_child(c)
		cars.append(c)
	if watch != "":
		# Watch mode: canonical harness seed (identical demand for every
		# strategy), scenario routes committed in the PLAN phase exactly like a
		# player's, then straight into the run - no briefing, no editing.
		rng.seed = Scenarios3.SEEDS[level.id]
		var rs: Array = Discovered3.route_set(level.id) if watch == "best" \
				else Scenarios3.route_set(level.id, watch)
		for i in mini(rs.size(), CARDS.size()):
			commit_route(i, Scenarios3.cells_of(rs[i]), Scenarios3.closed_of(rs[i]),
					Scenarios3.home_of(rs[i]))
		start_run()
	else:
		rng.randomize() # normal play is unseeded; the harness overrides rng.seed
		hud.show_briefing()
	hud.refresh_cards()


func _process(delta: float) -> void:
	if state != State.PLAYING:
		return
	advance(delta * time_scale)
	_reflow_queues()
	hud.refresh_stats()


## One logic step of `dt` game-seconds (also driven directly by the harness).
func advance(dt: float) -> void:
	if dt <= 0.0:
		return
	elapsed += dt
	if auto_spawn:
		_spawn_tick(dt)
	for c in cars:
		if c != null:
			c.tick(dt)
	for p in active_passengers:
		p.tick(dt)
	if _passengers_dirty:
		_passengers_dirty = false
		var keep: Array = []
		for p in active_passengers:
			if p.active:
				keep.append(p)
		active_passengers = keep


## Average per-passenger spawn interval right now (ramps over the session).
func current_interval() -> float:
	var s: Dictionary = level.spawn
	return lerpf(s.interval_start, s.interval_end,
			clampf(elapsed / float(s.ramp), 0.0, 1.0))


## Pulse spawning: bursts of burst_min..burst_max passengers `gap` s apart,
## then quiet for burst_size * interval (average rate == interval, but with
## visible lulls where cars go idle and door timing reads).
## The timers are consumed EXACTLY - a step is spent down to the instant each
## one fires and the remainder carries on into the next spawn - so the arrival
## sequence is the same whether the caller advances in 0.05 s or 1 s slices.
## (Before v4 the leftover past zero was thrown away, which quietly made a
## coarse search step spawn a slower crowd than the fine reporting step.)
func _spawn_tick(dt: float) -> void:
	var s: Dictionary = level.spawn
	var rem := dt
	var guard := 0
	while rem > 0.0 and guard < 256:
		guard += 1
		if burst_left > 0:
			if burst_timer > rem:
				burst_timer -= rem
				rem = 0.0
			else:
				rem -= burst_timer
				burst_timer = 0.0
				_spawn_random()
				burst_left -= 1
				burst_timer = s.gap
		else:
			if pulse_timer > rem:
				pulse_timer -= rem
				rem = 0.0
			else:
				rem -= pulse_timer
				pulse_timer = 0.0
				var n: int = rng.randi_range(s.burst_min, s.burst_max)
				burst_left = n
				burst_timer = 0.0 # first of the burst spawns immediately
				pulse_timer = n * current_interval()


# ---------------------------------------------------------------- phase flow

## Enter the editable PLAN phase. THE one way in: the briefing's PLAN button,
## ABORT during a run, and RETRY on a result overlay all land here. Routes are
## KEPT (that is the whole point of retry); everything else - counters, the
## passenger pool, the clock, the spawner, any car left mid-recall by the
## mid-run commit path - is reset, so a plan always starts from a clean
## building.
func to_plan() -> void:
	state = State.PLAN
	time_scale = 1.0
	drawing = false
	stroke = []
	stroke_closed = false
	served = 0
	lost = 0
	elapsed = 0.0
	endless = false
	log_served = []
	log_lost = []
	_clear_passengers() # also re-parks every car at its route start
	_reset_spawner()
	hud.hide_overlay()
	hud.refresh_cards()


## Commit the plan and start the simulation. THE "start run" entry point: the
## RUN button, watch mode, the balance harness and the depth tools all use it,
## and all of them commit their routes BEFORE calling it (see commit_route).
##
## It deliberately does NOT enforce ready_to_run(); that is the RUN BUTTON's
## gate. The search tools evaluate route-sets that leave a card undrawn on
## purpose, and an unrouted card simply parks.
func start_run() -> void:
	hud.hide_overlay()
	state = State.PLAYING
	_reset_spawner()


## RUN -> PLAN. Same reset as any other way into PLAN.
func abort_run() -> void:
	to_plan()


func next_level() -> void:
	Levels3.current = mini(Levels3.current + 1, Levels3.LEVELS.size() - 1)
	Levels3.watch_strategy = ""
	get_tree().change_scene_to_file("res://scenes/v3_main.tscn")


func to_level_select() -> void:
	Levels3.watch_strategy = ""
	get_tree().change_scene_to_file("res://scenes/v3_select.tscn")


## Watch overlays' "Watch Again": reload the scene with the same strategy
## (Levels3.watch_strategy is still set), so the seeded run replays exactly.
func watch_again() -> void:
	get_tree().change_scene_to_file("res://scenes/v3_main.tscn")


func _reset_spawner() -> void:
	pulse_timer = 2.0
	burst_left = 0
	burst_timer = 0.0


func _win() -> void:
	state = State.WIN
	hud.show_win(served, lost)


func _lose() -> void:
	state = State.LOSE
	hud.show_lose(served, lost)


func _clear_passengers() -> void:
	for p in passengers_node.get_children():
		p.active = false
		p.queue_free()
	active_passengers = []
	_passengers_dirty = false
	for r in waiting:
		waiting[r].clear()
	for c in cars:
		c.riders.clear()
		c.set_route(c.route) # re-park at route start


func set_speed(s: float) -> void:
	time_scale = s


# ---------------------------------------------------------------- input

## THE editing gate. Route editing is a PLAN-phase action and nothing else:
## during a RUN, on a result overlay, on the briefing, or in watch mode the
## network is frozen. Every editing entry point checks this - the drag
## handlers, chip selection, CLEAR, and commit_route itself - so there is no
## path (input, HUD, or API) that redraws a route while the sim is running.
func can_edit() -> bool:
	return watch == "" and state == State.PLAN


## Cards that cannot run as drawn: no route, or a route with < 2 room stops
## (the existing "car is parked" rule). RUN is gated on this being empty.
func cards_not_ready() -> Array:
	var out: Array = []
	for i in CARDS.size():
		if routes[i] == null or routes[i].stop_cells().size() < 2:
			out.append(CARDS[i].name)
	return out


func ready_to_run() -> bool:
	return cards_not_ready().is_empty()


func _unhandled_input(event: InputEvent) -> void:
	if not can_edit():
		return # RUN / RESULT / watch mode: the grid is read-only
	if event is InputEventScreenTouch:
		if event.pressed:
			_begin_stroke(event.position)
		else:
			_end_stroke()
	elif event is InputEventScreenDrag:
		_extend_stroke(event.position)


func select_card(i: int) -> void:
	if not can_edit():
		return # chips are display-only outside PLAN
	selected_card = -1 if selected_card == i else i
	drawing = false
	stroke = []
	stroke_closed = false
	reject_until_ms = 0 # a fresh selection clears any stale rejection hint
	hud.refresh_cards()


func _begin_stroke(pos: Vector2) -> void:
	if selected_card < 0 or not can_edit():
		return
	var cell := Grid3.cell_at(pos)
	if cell.x < 0 or not _drawable(cell):
		return
	drawing = true
	stroke = [cell]
	stroke_closed = false


func _extend_stroke(pos: Vector2) -> void:
	if not drawing:
		return
	var cell := Grid3.cell_at(pos)
	if cell.x < 0:
		return
	stroke_try_extend(cell)


## Grow the active stroke toward `cell` (the finger's cell this drag sample).
## MAGNETIC HEAD: picture the head as a magnet pulled toward the finger, free to
## slide along the path it has drawn. One idea, applied in both directions and
## purely positional (drag speed is irrelevant):
##   RETRACT — pop the head while the cell BEHIND it is strictly closer to the
##     finger than the head is. Gives straight-run snapping, cutting back around
##     corners, and rerouting at a junction (the abandoned leg pops off, then the
##     outbound walk below draws the new one).
##   EXTEND — push the head onward while a legal neighbour is strictly closer to
##     the finger than the head is, preferring the axis with the most ground left
##     to cover. Gives straight-line fill across a fast skip and corners that
##     turn on their own, without ever teleporting: the walk moves one adjacent
##     legal cell at a time, so a wall or the stroke's own body simply stops it
##     where it stands.
## A finger that pulls neither way — a sideways graze of an earlier part of the
## path — makes nothing closer, so the stroke holds still (the graze collides).
## CLOSING (v3.4): dragging onto stroke[0] when the stroke has >= 4 cells and
## the last cell is orthogonally adjacent to it CLOSES the loop — checked before
## retract. While closed, forward drags are ignored and retracting is impossible;
## reversing onto the TAIL cell REOPENS the loop, after which retract continues.
## Returns true if the stroke changed.
func stroke_try_extend(cell: Vector2i) -> bool:
	if stroke.is_empty():
		return false
	if stroke_closed:
		if cell == stroke.back():
			stroke_closed = false # reopen: remove the closing link only
			return true
		return false # closed: any other drag is ignored
	if cell == stroke.back():
		return false
	# Closing takes precedence over retract when the head is adjacent to start.
	if cell == stroke[0] and stroke.size() >= 4:
		var dh: Vector2i = cell - stroke.back()
		if absi(dh.x) + absi(dh.y) == 1:
			stroke_closed = true # close the loop; stroke cells unchanged
			return true
	# Magnetic retract: slide the head back toward the finger along the path.
	var changed := false
	while stroke.size() >= 2:
		var h: Vector2i = stroke[stroke.size() - 1]
		var p: Vector2i = stroke[stroke.size() - 2]
		if _md(cell, p) < _md(cell, h):
			stroke.remove_at(stroke.size() - 1)
			changed = true
		else:
			break
	# Magnetic extend: walk the head toward the finger one legal cell at a time,
	# each step strictly closer (so the walk always terminates), taking the axis
	# with the most ground left to cover first so corners turn naturally.
	var guard := 0
	while guard < MAX_STROKE_WALK:
		guard += 1
		var h: Vector2i = stroke[stroke.size() - 1]
		if h == cell:
			break
		var d: Vector2i = cell - h
		var steps: Array = []
		if absi(d.x) >= absi(d.y):
			if d.x != 0:
				steps.append(Vector2i(signi(d.x), 0))
			if d.y != 0:
				steps.append(Vector2i(0, signi(d.y)))
		else:
			if d.y != 0:
				steps.append(Vector2i(0, signi(d.y)))
			if d.x != 0:
				steps.append(Vector2i(signi(d.x), 0))
		var moved := false
		for s in steps:
			var n: Vector2i = h + s
			if _drawable(n) and not stroke.has(n):
				stroke.append(n)
				changed = true
				moved = true
				break
		if not moved:
			break # walled in, or blocked by the stroke's own body
	return changed


## Manhattan distance between two cells (the metric the magnetic pull uses).
func _md(a: Vector2i, b: Vector2i) -> int:
	return absi(a.x - b.x) + absi(a.y - b.y)


## Release. A drag of two or more cells commits a route; a TAP (the stroke
## never left its first cell) sets or clears that card's HOME cell instead -
## see toggle_home. Both are PLAN-phase actions and nothing else.
func _end_stroke() -> void:
	if not drawing:
		return
	drawing = false
	if selected_card >= 0 and stroke.size() == 1:
		toggle_home(selected_card, stroke[0])
	elif selected_card >= 0 and stroke.size() > 0:
		commit_route(selected_card, stroke, stroke_closed)
	stroke = []
	stroke_closed = false


# ---------------------------------------------------------------- route edits

## Commit `cells` as card i's route (REPLACES any previous route), the way the
## player does: in the PLAN phase, where nothing is running, so the car simply
## APPEARS at the new start (Car3.set_route). `closed` marks a loop (stroke
## closed onto its head — the car will travel forward around the cycle
## forever).
##
## REFUSED outside PLAN/BRIEFING. That is the v4 rule in one line: the network
## is frozen for the whole run, so no caller — player, harness or tool — can
## reshape it mid-simulation by accident. The harness and the depth tools
## therefore commit first and call start_run() after; commit_route_mid_run()
## is the deliberate way in for the code that still tests recall/redeploy.
##
## Geometry is checked by Route3.validate (the drag code can only produce
## legal strokes, so this is the safety net for PROGRAMMATIC callers: the
## harness, watch mode and the search tools). An illegal route is REJECTED —
## logged, the previous route kept, no crash. An EMPTY cell array clears the
## card, exactly as before. Returns true when the commit went through.
## `home` (v4 phase 2, optional) is the car's HOME CELL, part of the plan just
## like the polyline: pass a cell of `cells` and an idle empty car deadheads
## there instead of parking wherever it happens to be. Scenario data, the
## harness, watch mode and the depth tools all express it through this one
## argument, so a route-set is always "where it goes" plus "where it waits".
func commit_route(i: int, cells: Array, closed := false, home = null) -> bool:
	if state != State.PLAN and state != State.BRIEFING:
		push_error("commit_route(%d) refused: routes are locked outside PLAN" % i)
		return false
	return _commit(i, cells, closed, false, home)


## MID-RUN commit — the v3.3 recall -> ghost countdown -> redeploy path
## (Car3.apply_route). NOTHING in the v4 player flow calls this: every commit
## happens in PLAN, so every car deploys instantly and the recall machinery
## never fires during a run. It is kept, working and tested, because it is
## still correct and a future "place-only mid-run" mode wants it; tests/
## balance.gd drives the redeploy checks through here rather than through a
## player path that no longer exists.
func commit_route_mid_run(i: int, cells: Array, closed := false) -> bool:
	return _commit(i, cells, closed, true)


func _commit(i: int, cells: Array, closed: bool, mid_run: bool, home = null) -> bool:
	var r: Route3 = null
	if cells.size() > 0:
		var err := Route3.validate(cells, closed and cells.size() >= 4,
				cars[i].width)
		if err != "":
			push_error("commit_route(%d) rejected: %s" % [i, err])
			_set_reject_hint(i, cells, err)
			return false
		r = Route3.new()
		r.cells = cells.duplicate()
		r.closed = closed and cells.size() >= 4
	routes[i] = r
	if mid_run:
		cars[i].apply_route(r) # recall riders, then redeploy after a countdown
	else:
		cars[i].set_route(r) # PLAN: nothing is running, so the car just appears
	# The home cell belongs to the ROUTE: an explicit one is taken if it is on
	# the new polyline, and any older one that the redraw stranded is dropped.
	if home != null:
		cars[i].set_home_cell(home if r != null and r.index_of(home) != -1 else null)
	elif cars[i].home_cell != null \
			and (r == null or r.index_of(cars[i].home_cell) == -1):
		cars[i].set_home_cell(null)
	replan_all()
	hud.refresh_cards()
	return true


## Park the reason a commit was refused so hud3 can surface it on the hint
## line in the card's colour. A too-narrow corridor gets a width-specific
## message (the common case now that pod/cargo widths differ); anything else a
## programmatic caller slipped through falls back to the raw validator reason.
func _set_reject_hint(i: int, cells: Array, err: String) -> void:
	reject_card = i
	reject_until_ms = Time.get_ticks_msec() + 4000
	var cw: int = cars[i].width
	var mw := Grid3.route_min_gate_width(cells)
	if mw < cw:
		reject_msg = "%s is width %d - that corridor only fits width %d. Go around." % [
				CARDS[i].name, cw, mw]
	else:
		reject_msg = "%s can't run there: %s" % [CARDS[i].name, err]


## True when the selected card may draw through `cell`: passable, and not a
## gate corridor narrower than the selected car. This is the magnetic head's
## half of the corridor rule - a too-narrow corridor cell is felt as a wall
## while drawing, so the rejection reads as resistance rather than a silent
## commit failure. With no card selected (or every current width-2 car into a
## width-2 corridor) it is exactly Grid3.passable, so existing levels are
## unchanged.
func _drawable(cell: Vector2i) -> bool:
	if not Grid3.passable(cell):
		return false
	if selected_card < 0 or selected_card >= cars.size():
		return true
	var gi := Grid3.gate_group_of(cell)
	if gi != -1 and Grid3.gate_group_width(gi) < cars[selected_card].width:
		return false
	return true


## PLAN-phase tap on a cell of card i's route: make it the car's HOME (idle
## empty cars deadhead there and wait) or, if it already is, clear it. Returns
## true when something changed. Taps anywhere else are ignored.
func toggle_home(i: int, cell: Vector2i) -> bool:
	if not can_edit() or i < 0 or i >= cars.size():
		return false
	var r = routes[i]
	if r == null or r.index_of(cell) == -1:
		return false
	cars[i].set_home_cell(null if cars[i].home_cell == cell else cell)
	hud.refresh_cards()
	return true


## CLEAR button. PLAN-phase only, like every other edit.
func clear_route(i: int) -> void:
	if not can_edit():
		return
	_commit(i, [], false, false)


## A recalled car dumped a rider at `cell` (a room stop of its OLD route):
## either that's their destination (served) or they rejoin the waiting pool
## there with a fresh plan against the current network.
func on_recall_drop(p, cell: Vector2i) -> void:
	p.riding = null
	p.cur_cell = cell
	if not p.legs.is_empty():
		p.legs = []
	if cell == p.dest_cell:
		on_served(p)
		return
	_compute_path_for(p)
	waiting[cell].append(p)


func route_warning(i: int) -> bool:
	return routes[i] != null and routes[i].stop_cells().size() < 2


# ---------------------------------------------------------------- gates

## FIFO WIDTH-SHARED corridor per gate GROUP (a whole run of contiguous gate
## cells). The corridor has a width; a car may be inside only if
##   car.width <= corridor.width  AND  sum of widths inside <= corridor.width,
## and only the FRONT of the queue is ever admitted (strict FIFO, so a stream
## of pods can never starve a standard waiting behind them).
##
## With the default corridor width of 2 and every pre-v4 car at width 2 this
## is EXACTLY the old one-car mutex: the first car takes all the width there
## is, and the next request cannot fit until it leaves.
func gate_request(car, group: int) -> bool:
	var g: Dictionary = gates[group]
	if g.holders.has(car):
		return true
	if car.width > g.width:
		return false # too wide for this corridor, ever: never queue for it
	if not g.queue.has(car):
		g.queue.append(car)
	if g.queue[0] == car and g.used + car.width <= g.width:
		g.queue.pop_front()
		g.holders.append(car)
		g.used += car.width
		return true
	return false


## Would gate_request() succeed right now? A PURE PREDICATE - it never queues
## the car. Car3's braking lookahead asks it, because a car that cannot get
## into the corridor ahead has to arrive at its mouth already stopped.
func gate_free_for(car, group: int) -> bool:
	var g: Dictionary = gates[group]
	if g.holders.has(car):
		return true
	if car.width > g.width:
		return false
	if not g.queue.is_empty() and g.queue[0] != car:
		return false
	return g.used + car.width <= g.width


func gate_release(car, group: int) -> void:
	var g: Dictionary = gates[group]
	if g.holders.has(car):
		g.holders.erase(car)
		g.used -= car.width


## Remove a car from every gate queue/lock (route replaced or cleared).
func gate_cancel(car) -> void:
	for gi in gates:
		gates[gi].queue.erase(car)
		gate_release(car, gi)


# ---------------------------------------------------------------- pathfinding

## Recompute paths for every WAITING passenger. Called on any route commit or
## clear. Riders keep their current leg and replan on alight.
func replan_all() -> void:
	for r in waiting:
		for p in waiting[r]:
			_compute_path_for(p)


func _compute_path_for(p) -> void:
	var path = Pathfind3.find_path(p.cur_cell, p.dest_cell, cars, p.salt, p.width)
	if path == null:
		p.legs = []
		p.no_path = true
	else:
		p.legs = path
		p.no_path = false


# ---------------------------------------------------------------- passengers

## Weighted pick from the level's type mix.
func _pick_type() -> String:
	var mix: Dictionary = level.mix
	var total := 0.0
	for t in mix:
		total += mix[t]
	var roll := rng.randf() * total
	for t in mix:
		roll -= mix[t]
		if roll <= 0.0:
			return t
	return mix.keys().back()


func _pick_room(group: Array, avoid: Vector2i = Vector2i(-1, -1)) -> Vector2i:
	var pool := group.filter(func(c): return c != avoid)
	if pool.is_empty():
		pool = group
	return pool[rng.randi_range(0, pool.size() - 1)]


func _spawn_random() -> void:
	var t := _pick_type()
	var o: Vector2i
	var d: Vector2i
	# type_rooms (v4 axiom levels): a type may be pinned to its own origin/dest
	# room lists, the same way execs are, so "big deliveries run the dock->top
	# freight lane" is expressible without a width-3 party appearing on an
	# ordinary commute. Existing levels omit the key, so their spawn sequence -
	# and the determinism fingerprint - is untouched. Exec stays its own branch.
	var tr: Dictionary = level.get("type_rooms", {})
	if tr.has(t):
		o = _pick_room(tr[t].from)
		d = _pick_room(tr[t].to, o)
	elif t == "exec" and not level.exec_origins.is_empty() \
			and not level.exec_dests.is_empty():
		# Execs use only the level-designated origin/destination rooms.
		o = _pick_room(level.exec_origins)
		d = _pick_room(level.exec_dests, o)
	else:
		if t == "exec":
			t = "visitor" # level configured exec weight but no rooms: degrade
		# Weighted trip table between named room groups.
		var groups: Dictionary = level.groups
		var trips: Array = level.trips
		var total := 0.0
		for row in trips:
			total += row.w
		var roll := rng.randf() * total
		var picked: Dictionary = trips.back()
		for row in trips:
			roll -= row.w
			if roll <= 0.0:
				picked = row
				break
		o = _pick_room(groups[picked.from])
		d = _pick_room(groups[picked.to], o)
	if o == d:
		return # degenerate config (single shared room); skip this spawn
	spawn_passenger(t, o, d)


func spawn_passenger(ptype: String, origin: Vector2i, dest: Vector2i) -> Passenger3:
	var p := Passenger3.new()
	p.setup(self, ptype, origin, dest)
	p.salt = rng.randf()
	passengers_node.add_child(p)
	active_passengers.append(p)
	waiting[origin].append(p)
	_compute_path_for(p)
	return p


## A rider stepped out of a car at room cell: served, or transfer + replan.
func on_alight(p, cell: Vector2i) -> void:
	p.riding = null
	if not p.legs.is_empty():
		p.legs.pop_front()
	p.cur_cell = cell
	if cell == p.dest_cell:
		on_served(p)
	else:
		_compute_path_for(p) # always replan from the transfer room
		waiting[cell].append(p)


func on_served(p) -> void:
	p.active = false
	_passengers_dirty = true
	log_served.append({"type": p.ptype, "origin": p.origin_cell,
			"dest": p.dest_cell, "wait": p.wait_time, "rides": p.rides})
	p.queue_free()
	served += 1
	if state == State.PLAYING and not endless and served >= QUOTA:
		_win()


func on_expired(p) -> void:
	_passengers_dirty = true
	waiting[p.cur_cell].erase(p)
	log_lost.append({"type": p.ptype, "origin": p.origin_cell,
			"dest": p.dest_cell, "wait": p.wait_time, "rides": p.rides})
	p.queue_free()
	lost += 1
	if state == State.PLAYING and not endless and lost >= MAX_LOST:
		_lose()


## Total game-seconds cars of this session spent blocked at gates (stat).
func gate_wait_total() -> float:
	var t := 0.0
	for c in cars:
		if c != null:
			t += c.gate_wait_total
	return t


## Total gate-corridor lock acquisitions this session (stat / harness).
func gate_transit_total() -> int:
	var n := 0
	for c in cars:
		if c != null:
			n += c.gate_transits
	return n


## Stack waiting parties inside their room cell (queue beside the room),
## packing each row by the WIDTH each party actually draws - a big delivery is
## three times a visitor, and two of them overlapping would hide exactly the
## thing the player has to plan around. Visual only; nothing here is read by
## the simulation.
func _reflow_queues() -> void:
	var band := Grid3.CELL - 8.0
	for r in waiting:
		var base := Grid3.cell_center(r)
		var x := 0.0
		var row := 0
		for p in waiting[r]:
			var w: float = p.body_w() + 4.0
			if x > 0.0 and x + w > band:
				row += 1
				x = 0.0
			p.position = base + Vector2(-band / 2.0 + x + w / 2.0, 30.0 - row * 22.0)
			x += w
