extends Control
## Level select (the project's MAIN scene). One row per Levels3 entry:
## a big PLAY button (id + name + one-line thesis) plus WATCH NAIVE /
## WATCH THESIS buttons that replay the balance scenarios in-game (routes
## pre-drawn from Scenarios3, canonical seed, editing disabled). Picking
## anything sets Levels3.current + Levels3.watch_strategy and loads the game
## scene (main3 reads both in _ready).

func _ready() -> void:
	set_anchors_preset(Control.PRESET_FULL_RECT)
	var bg := ColorRect.new()
	bg.color = Color(0.09, 0.09, 0.11)
	add_child(bg)
	bg.set_anchors_preset(Control.PRESET_FULL_RECT)
	var center := CenterContainer.new()
	add_child(center)
	center.set_anchors_preset(Control.PRESET_FULL_RECT)
	var box := VBoxContainer.new()
	box.add_theme_constant_override("separation", 22)
	center.add_child(box)
	var title := Label.new()
	title.text = "PATH DRAWING - PICK A LEVEL"
	title.add_theme_font_size_override("font_size", 36)
	title.add_theme_color_override("font_color", Color(0.95, 0.85, 0.5))
	title.horizontal_alignment = HORIZONTAL_ALIGNMENT_CENTER
	box.add_child(title)
	for i in Levels3.LEVELS.size():
		box.add_child(_make_row(i))


func _make_row(i: int) -> HBoxContainer:
	var lv: Dictionary = Levels3.LEVELS[i]
	var col := Color(0.93, 0.58, 0.16) if lv.id != "X-1" else Color(0.5, 0.55, 0.65)
	var row := HBoxContainer.new()
	row.add_theme_constant_override("separation", 10)
	var play := Button.new()
	play.text = "%s  %s\n%s" % [lv.id, str(lv.name).to_upper(), lv.thesis]
	play.custom_minimum_size = Vector2(470, 130)
	play.add_theme_font_size_override("font_size", 21)
	play.add_theme_stylebox_override("normal", _style(col))
	play.pressed.connect(_start.bind(i, ""))
	row.add_child(play)
	var wbox := VBoxContainer.new()
	wbox.add_theme_constant_override("separation", 10)
	row.add_child(wbox)
	var sets: Dictionary = Scenarios3.route_sets(lv.id)
	# WATCH BEST only appears where the depth search actually discovered a
	# route-set for this level (scripts/v3/discovered3.gd, generated by
	# tools/run_depth.gd) — optimizer output has to be eyeballed, not trusted.
	var strategies: Array = ["naive", "thesis"]
	if Discovered3.has(lv.id):
		strategies.append("best")
	for strat in strategies:
		if strat != "best" and not sets.has(strat):
			continue
		var tone := Color(0.35, 0.72, 0.42)
		if strat == "naive":
			tone = Color(0.75, 0.35, 0.30)
		elif strat == "best":
			tone = Color(0.45, 0.48, 0.85)
		var wb := Button.new()
		wb.text = "WATCH\n%s" % strat.to_upper()
		wb.custom_minimum_size = Vector2(150, 60)
		wb.add_theme_font_size_override("font_size", 17)
		wb.add_theme_stylebox_override("normal", _style(tone))
		wb.pressed.connect(_start.bind(i, strat))
		wbox.add_child(wb)
	return row


func _start(index: int, strategy: String) -> void:
	Levels3.current = index
	Levels3.watch_strategy = strategy
	get_tree().change_scene_to_file("res://scenes/v3_main.tscn")


func _style(col: Color) -> StyleBoxFlat:
	var sb := StyleBoxFlat.new()
	sb.bg_color = col.darkened(0.55)
	sb.border_color = col
	sb.set_border_width_all(3)
	sb.set_corner_radius_all(10)
	return sb
